apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-component
  description: Test Component
  tags:
    - java
    - data
spec:
  type: service
  lifecycle: experimental
  owner: carlos.corton@altia.es